# Generated by Django 3.0.6 on 2020-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='fullname',
            new_name='fisrtname',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='recovery_mail',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
