# Generated by Django 3.0.6 on 2020-05-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_auto_20200522_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='fisrtname',
            new_name='firstname',
        ),
    ]
