# Generated by Django 3.0.6 on 2020-06-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_auto_20200522_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productdesc', models.CharField(max_length=1000)),
                ('productprice', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='shop/media')),
            ],
        ),
    ]
