# Generated by Django 3.0.6 on 2020-06-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='productimage',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
